setting:
  host: "127.0.0.1"
  port: "4433"
  tls_cert_file: "cert/cert.pem"
  tls_key_file: "cert/key.pem"

inputs:
- tag: source_alpha
  module: transform-regex
  option:
    exp: "(?s)^(?P<timestamp>\\w{3}\\s+\\d{1,2}\\s+\\d{2}:\\d{2}:\\d{2})\\s+(?P<host>[\\w-]+(?:\\s+[\\w-]+)*)\\s+(?P<process>[\\w-]+\\[\\d+\\])?:\\s+(?P<message>.+)$"
  produce:
    type: http
    host: "localhost"
    port: "3000"

- tag: source_beta
  module: transform-demo
  option:
    example: ""
  produce:
    type: kafka
    bootstrap_server: "localhost:9092"
    topic: quickstart-events

